# Generated by Django 4.2.6 on 2023-10-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminstrator_app', '0002_branchsetup_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_no', models.CharField(max_length=3)),
                ('center_name', models.CharField(max_length=350)),
                ('center_address', models.CharField(max_length=550)),
                ('meeting_date', models.CharField(max_length=100)),
                ('next_meeting_date', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator_app.branchsetup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminstrator_app.branchsetup')),
                ('center_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.centerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(max_length=15)),
                ('date_of_birth', models.CharField(max_length=150)),
                ('citizenship_no', models.CharField(max_length=150)),
                ('issue_date', models.CharField(max_length=150)),
                ('issue_place', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=150)),
                ('municipilaty', models.CharField(max_length=150)),
                ('worda', models.IntegerField(default=0)),
                ('village', models.CharField(max_length=150)),
                ('father', models.CharField(max_length=150)),
                ('spouse', models.CharField(max_length=150)),
                ('spouse_dob', models.CharField(max_length=150)),
                ('s_citizenship', models.CharField(max_length=150)),
                ('s_issue_date', models.CharField(max_length=150)),
                ('s_place', models.CharField(max_length=150)),
                ('s_occupation', models.CharField(max_length=350)),
                ('father_inlow', models.CharField(max_length=150)),
                ('tdistrict', models.CharField(max_length=150)),
                ('tmunicipilaty', models.CharField(max_length=150)),
                ('tworda', models.IntegerField(default=0)),
                ('tvillage', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='media/images')),
                ('citizenship_copy', models.ImageField(upload_to='media/images')),
                ('signature_card', models.ImageField(upload_to='media/images')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminstrator_app.branchsetup')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.centerdetails')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.groupsetup')),
            ],
        ),
    ]
