# Generated by Django 4.2.6 on 2023-10-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator_app', '0002_branchsetup_branch_code'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsetup',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchsetup', to='adminstrator_app.branchsetup'),
        ),
    ]
