# Generated by Django 4.2.6 on 2023-10-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator_app', '0002_branchsetup_branch_code'),
        ('member', '0002_alter_groupsetup_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=5)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminstrator_app.branchsetup')),
                ('center_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.centerdetails')),
            ],
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.groupcreate'),
        ),
        migrations.DeleteModel(
            name='GroupSetup',
        ),
    ]
